#!/usr/bin/env bash
set -euo pipefail

RESOURCE_GROUP="${RESOURCE_GROUP:?RESOURCE_GROUP is required}"
WEBAPP_NAME="${WEBAPP_NAME:?WEBAPP_NAME is required}"

az webapp config appsettings set \
  --resource-group "$RESOURCE_GROUP" \
  --name "$WEBAPP_NAME" \
  --settings \
    APP_ENV=prod \
    WEB_APP_PORT=8000 \
    AZURE_TENANT_ID="$AZURE_TENANT_ID" \
    AZURE_CLIENT_ID="$AZURE_CLIENT_ID" \
    AZURE_CLIENT_SECRET="$AZURE_CLIENT_SECRET" \
    OIDC_AUTHORITY_URL="$OIDC_AUTHORITY_URL" \
    OIDC_CALLBACK_URL_TEST="$OIDC_CALLBACK_URL_TEST" \
    OIDC_CALLBACK_URL_PROD="$OIDC_CALLBACK_URL_PROD" \
    SQL_SERVER="$SQL_SERVER" \
    SQL_DATABASE="$SQL_DATABASE" \
    OPENAI_ENDPOINT="$OPENAI_ENDPOINT" \
    OPENAI_API_VERSION="$OPENAI_API_VERSION" \
    OPENAI_DEPLOYMENT="$OPENAI_DEPLOYMENT" \
    GOOGLE_NEWS_RSS_BASE_URL="$GOOGLE_NEWS_RSS_BASE_URL" \
    SQL_MAX_ROWS=100 \
    MOCK_AUTH_ENABLED=false
